version: "3"
services:
  python-aws-suites:
    container_name: container-aws-suites
    env_file:
      - .env
    build:
      context: ./python
      dockerfile: Dockerfile
      target: debug
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        PYTHON: ${PYTHON}
    ports:
      - "9999:8888"
      - "5678:5678"
    volumes:
      - ./www:/var/www
      - ${PROJECTS_FOLDER}:/var/www/projects
    command: ["supervisord", "-n"]